# Servicios comunes para la GPT API

version: '3.9'

networks:
  common:
    external: true
    name: ${COMMON_NET}
  ingress:
    external: true
    name: ${INGRESS_NET}

services:  
  interface:
    image: ${INTERFACE_IMAGE-alexanderditzend/gpt-api:0.1.0}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-interface-http.rule=Host(`${INTERFACE_DOMAIN}`)
        - traefik.http.routers.${NAME}-interface-http.entrypoints=http
        - traefik.http.routers.${NAME}-interface-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-interface-https.rule=Host(`${INTERFACE_DOMAIN}`) || Host(`www.${INTERFACE_DOMAIN}`)
        - traefik.http.routers.${NAME}-interface-https.entrypoints=https
        - traefik.http.routers.${NAME}-interface-https.tls=true
        - traefik.http.routers.${NAME}-interface-https.tls.certresolver=le
        - traefik.http.services.${NAME}-interface.loadbalancer.server.port=80      
      resources:
        limits:
          cpus: '${INTERFACE_CPU_LIMIT-4}'
          memory: ${INTERFACE_MEMORY_LIMIT-500M}
        reservations:
          cpus: '${INTERFACE_CPU_RESERVATION-0.25}'
          memory: ${INTERFACE_MEMORY_RESERVATION-500M}
      replicas: ${INTERFACE_REPLICAS-1}
      placement:
        constraints:
          - node.role == ${INTERFACE_NODE-worker}
    ports:
      - ${INTERFACE_PORT-}:80
    networks:
      - common
      - ingress
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENTIMENT_URL=${SENTIMENT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ALLOW_INTENT_CREATION=${ALLOW_INTENT_CREATION}
      - ALLOW_ENTITY_CREATION=${ALLOW_ENTITY_CREATION}
      - ALLOW_INDEX_DELETION=${ALLOW_INDEX_DELETION}
      - KB_CONVERSATIONAL=${KB_CONVERSATIONAL}
      - KB_TEMPERATURE=${KB_TEMPERATURE}
      - TOP_P=${TOP_P}
      - MAX_TOKENS=${MAX_TOKENS}
      - REPEAT_PENALTY=${REPEAT_PENALTY}
      - STOP_SEQUENCE=${STOP_SEQUENCE}
      - RETURN_PROMPT=${RETURN_PROMPT}
      - RETURN_COMPLETION=${RETURN_COMPLETION}
      - RETURN_ALL=${RETURN_ALL}
      - INCLUDE_PREFIX=${INCLUDE_PREFIX}